name: ðŸ› Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - bushvin
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report!
        âš 
        Verify first that your issue is not [already reported on
        GitHub](../search?q=is%3Aissue&type=issues) and keep in mind that we may have to keep
        the current behavior because [every change breaks someone's
        workflow](https://xkcd.com/1172/).
        We try to be mindful about this.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: foundryvtt_version
    attributes:
      label: Foundry VTT version
      description: Please enter your Foundry VTT version and build number
      placeholder: ex 11.315
    validations:
      required: true
  - type: dropdown
    id: game_system
    attributes:
      label: Game system
      description: Please enter the name of your game system
      options:
        - dnd5e
        - pf2e
        - pfrpg
    validations:
      required: true
  - type: input
    id: game_system_version
    attributes:
      label: Game system version
      description: Please enter the version of your game system
      placeholder: ex 5.12.0
    validations:
      required: true
  - type: input
    id: module_version
    attributes:
      label: actor-export module version
      description: Please enter the version of the module
      placeholder: ex 0.0.1
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: provider
    attributes:
      label: What Provider is affected?
      multiple: true
      options:
        - Bushvin's modified PF2e Remaster Character sheet
        - Bushvin's PF2e Remaster Character sheet (deprecated)
        - Dungeons & Dragons 5th edition Character sheets
        - PF2e Remaster Character sheet (original)
        - PF2e Scribe Generator
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: textarea
    id: actor
    attributes:
      label: Sample Actor
      description: >
        Please paste your exported actor here.
        Go to your Actors Sidebar tab, right-click the actor (character) and select "Export Data".
      render: JSON
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Please add any attachments here

