name: "actor-export CD"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  fvtt_minimum: 11
  fvtt_verified: 11
  fvtt_dry_run: false
  fvtt_module_id: actor-export

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Print module version
      run: |
        echo "github.ref_name: ${{ github.ref_name }}"

    - name: Retrieve previous version
      run: |
        echo "previous_tag=$(git tag | sort |tail -n2|head -n1)" >> $GITHUB_ENV

    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{ github.ref_name }}
        url: https://github.com/${{ github.repository }}
        manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
        download: https://github.com/${{ github.repository }}/releases/latest/download/${{ env.fvtt_module_id }}.zip

    - name: Zip files
      run: |
        rm -f ./${{ env.fvtt_module_id }}.zip;
        set -eu;
        7z a -tzip ./${{ env.fvtt_module_id }}.zip . \
          '-x!*.git*' '-x!assets' '-x!src' '-x!package*.json' '-x!.vscode' '-x!ansible' '-x!node_modules' '-x!tmp' '-x!.prettier*' '-x!providers/*/wiki'

    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1.13.0
      with:
        allowUpdates: false
        artifacts: "module.json,${{ env.fvtt_module_id }}.zip"
        draft: false
        generateReleaseNotes: true
        name: ${{ env.systemVersion }}
        prerelease: false
        tag: ${{ env.systemVersion }}
        token: ${{ secrets.GITHUB_TOKEN }}

  notify_matrix_elaba_net:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - name: 'Notify users on #actor-export-general:matrix.elaba.net'
      run: >
        curl https://matrix.elaba.net/hookshot/webhook/${{ secrets.HOOKSHOT_WEBHOOK_UUID }}
          --request POST
          --header "Content-Type: application/json"
          --data '{"text": "A new release of **${{ env.fvtt_module_id }}** is published: **${{ github.ref_name }}**"}'

  notify_discord:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Retrieve previous version
        run: |
          echo "previous_tag=$(git tag | sort |tail -n2|head -n1)" >> "$GITHUB_ENV"

      - name: Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          message: |
            A new release of ${{ env.fvtt_module_id }} is published: `${{ github.ref_name }}`.

  publish_foundry:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
      - name: Submit package to FoundryVTT Package Release API
        run: |
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version/" \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.FOUNDRYVTT_RELEASE_TOKEN }}" \
            -d '{
              "id": "${{ env.fvtt_module_id }}",
              "dry-run": ${{ env.fvtt_dry_run }},
              "release": {
                "version": "${{ github.ref_name }}",
                "manifest": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/module.json",
                "notes": "https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md",
                "compatibility": {
                  "minimum": "${{ env.fvtt_minimum }}",
                  "verified": "${{ env.fvtt_verified }}"
                }
              }
            }'
