name: actor-export CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
    branches:
      - main
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          github_token: '${{ secrets.PRETTIER_GITHUB_TOKEN }}'
          file_pattern: '*.js'
