name: "Foundry VTT Pf2e module"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  fvtt_minimum: 11
  fvtt_verified: 11
  fvtt_dry_run: true
  fvtt_module_id: actor-export

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          message: "A new release of ${{ env.fvtt_module_id }} is published: 0.0.7. Go get it!"
